version: '3'
services:
  lollms:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=python:3.10
    ports:
      - 9601:9601
    volumes:
      - ./data:/app/data
      